---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
spec:
  replicas: 2
  config: {}
  resources:
    limits:
      memory: 1Gi
      cpu: 2
    requests:
      memory: 1Gi
      cpu: 500m
  jvmOptions:
    "-Xmx": 256M
    "-Xms": 256M
