---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    replicas: 2
    jvmOptions:
      "-Xmx": 512M
      "-Xms": 512M
    resources:
      limits:
        memory: 2Gi
        cpu: 1
      requests:
        memory: 2Gi
        cpu: 100m
  zookeeper:
    replicas: 1
    jvmOptions:
      "-Xmx": 256M
      "-Xms": 256M
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 100m
